#!/usr/bin/env bash
# Install nginix web server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html > /dev/null
echo "Hello World!" | sudo tee /var/www/html/index*html
sudo service nginx start
